name: Saga CI setup
description: Checkout the repo and set shared environment
inputs:
  ref:
    description: Optional git ref to check out
    required: false
  fetch-depth:
    description: Fetch depth for checkout
    required: false
    default: "0"
runs:
  using: composite
  steps:
    - name: Checkout (custom ref)
      if: ${{ inputs.ref != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Checkout (default ref)
      if: ${{ inputs.ref == '' }}
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Export shared env
      shell: bash
      run: echo "PBXPROJ_PATH=Saga/Saga.xcodeproj/project.pbxproj" >> "$GITHUB_ENV"
