// DESCRIPTION: Set up shell completions and app config

import Common
import Foundation

// MARK: - CLI

let cli = SimpleCLI(
  filePath: #filePath,
  notes: [
    "Only adds completions if not already present",
    "Writes Saga/Config/Config.xcconfig (overwrites)",
    "Runs 'brew bundle' from repo root (Brewfile: 1password-cli, swift-format)",
    "Ensures 1Password CLI is authenticated; pulls Contentful credentials from the saga vault",
    "Restart your shell or run 'source ~/.zshrc' to activate",
  ]
)

func parseArguments(_ args: [String]) throws {
  guard args.isEmpty else {
    throw ScriptError("Unknown argument: \(args.joined(separator: " "))")
  }
}

private enum ConfigDefaults {
  static let directoryName = "Config"
  static let opAccount = "my.1password.com"
  static let opVault = "saga"
  /// 1Password item names (synced to Config.xcconfig AS IS)
  static let items = [
    "CONTENTFUL_DELIVERY_API_KEY",
    "CONTENTFUL_DELIVERY_PREVIEW_API_KEY",
    "CONTENTFUL_MANAGEMENT_ACCESS_TOKEN",
    "CONTENTFUL_SPACE_ID",
  ]
}

private func configTemplate(values: [String: String]) -> String {
  let lines = ConfigDefaults.items.map { "  \($0) = \(values[$0] ?? "")" }.joined(separator: "\n")
  return """
    //
    //  Config.xcconfig
    //  Saga
    //
    //  Generated by `run bootstrap`.
    //

    // Configuration settings file format documentation can be found at:
    // https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project

    \(lines)
    """
}

private func resolveConfigValues() throws -> [String: String] {
  var values: [String: String] = [:]
  for item in ConfigDefaults.items {
    values[item] = try readOnePasswordSecret(vault: ConfigDefaults.opVault, item: item)
  }
  return values
}

private func writeConfigFile(repoRoot: String, values: [String: String]) throws {
  // Path is Saga/Saga/Config/ (source files are in Saga/Saga/, xcodeproj is in Saga/)
  let configDir = URL(fileURLWithPath: repoRoot)
    .appendingPathComponent("Saga")
    .appendingPathComponent("Saga")
    .appendingPathComponent(ConfigDefaults.directoryName)
  let configPath = configDir.appendingPathComponent("Config.xcconfig").path

  try FileManager.default.createDirectory(at: configDir, withIntermediateDirectories: true)
  try configTemplate(values: values).write(
    toFile: configPath,
    atomically: true,
    encoding: .utf8
  )
}

@main
struct BootstrapCommand {
  static func main() {
    runMain {
      let args = normalizeScriptArgs(
        Array(CommandLine.arguments.dropFirst()), scriptName: cli.scriptName)
      cli.preflight(args)
      try parseArguments(args)

      let repoRoot = gitRoot() ?? FileManager.default.currentDirectoryPath
      let completionsPath = URL(fileURLWithPath: repoRoot)
        .appendingPathComponent("scripts")
        .appendingPathComponent("completions.zsh")
        .path

      let zshrcPath = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".zshrc")
        .path

      print("Setting up Saga development environment...")

      let brewPath = try runCommand("which", ["brew"], allowFailure: true, emitOutput: false)
      if brewPath.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
        throw ScriptError("Homebrew is required. Install from https://brew.sh/ and re-run.")
      }

      let repoRootURL = URL(fileURLWithPath: repoRoot)
      print("Installing dependencies from Brewfile...")
      _ = try runCommand(
        "brew",
        ["bundle"],
        cwd: repoRootURL,
        emitOutput: true
      )

      if !isOnePasswordAuthenticated(account: ConfigDefaults.opAccount) {
        print("Authenticating with 1Password...")
        do {
          try signInToOnePassword(account: ConfigDefaults.opAccount)
        } catch {
          throw ScriptError(
            "1Password sign-in failed. Run: op signin --account \(ConfigDefaults.opAccount)"
          )
        }
      }

      let configValues = try resolveConfigValues()
      try writeConfigFile(repoRoot: repoRoot, values: configValues)
      print("Wrote Saga/Config/Config.xcconfig from 1Password")

      // Check if completions are already configured
      let zshrcExists = FileManager.default.fileExists(atPath: zshrcPath)
      var zshrcContent = ""
      if zshrcExists {
        zshrcContent = try String(contentsOfFile: zshrcPath, encoding: .utf8)
      }

      if zshrcContent.contains(completionsPath) {
        print("Completions already configured in \(zshrcPath)")
      } else {
        // Append completions source line
        let sourceLine = "\n# Saga repo script completions\nsource \"\(completionsPath)\"\n"
        let newContent = zshrcContent + sourceLine
        try newContent.write(toFile: zshrcPath, atomically: true, encoding: .utf8)
        print("Added completions to \(zshrcPath)")
      }

      print("")
      print("Done! Restart your shell or run: source ~/.zshrc")
      print("")
      print("Tab completion examples:")
      print("  run <TAB>          - list scripts")
      print("  run format --<TAB> - list script options")
    }
  }
}
