// DESCRIPTION: Set up shell completions and app config

import Common
import Foundation

// MARK: - CLI

let cli = SimpleCLI(
  filePath: #filePath,
  notes: [
    "Only adds completions if not already present",
    "Writes Saga/Config/Config.xcconfig (overwrites)",
    "Runs 'brew bundle' from repo root (Brewfile: 1password-cli, swift-format)",
    "Ensures 1Password CLI is authenticated; pulls Contentful credentials from the saga vault",
    "Restart your shell or run 'source ~/.zshrc' to activate",
  ]
)

func parseArguments(_ args: [String]) throws {
  guard args.isEmpty else {
    throw ScriptError("Unknown argument: \(args.joined(separator: " "))")
  }
}

private enum ConfigDefaults {
  static let directoryName = "Config"
  static let opAccount = "my.1password.com"
  static let opVault = "saga"
  static let spaceIDItem = "CONTENTFUL_SPACE_ID"
  static let accessTokenItem = "CONTENTFUL_ACCESS_TOKEN"
}

private struct ConfigValues {
  let spaceID: String
  let accessToken: String
}

private func configTemplate(values: ConfigValues) -> String {
  """
  //
  //  Config.xcconfig
  //  Saga
  //
  //  Generated by `run bootstrap`.
  //

  // Configuration settings file format documentation can be found at:
  // https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project

  CONTENTFUL_SPACE_ID = \(values.spaceID)
  CONTENTFUL_ACCESS_TOKEN = \(values.accessToken)
  """
}

private func resolveConfigValues() throws -> ConfigValues {
  let spaceID = try readOnePasswordSecret(
    vault: ConfigDefaults.opVault,
    item: ConfigDefaults.spaceIDItem
  )
  let accessToken = try readOnePasswordSecret(
    vault: ConfigDefaults.opVault,
    item: ConfigDefaults.accessTokenItem
  )
  return ConfigValues(spaceID: spaceID, accessToken: accessToken)
}

private func writeConfigFile(repoRoot: String, values: ConfigValues) throws {
  let sagaRoot = URL(fileURLWithPath: repoRoot).appendingPathComponent("Saga")
  let configDir = sagaRoot.appendingPathComponent(ConfigDefaults.directoryName)
  let configPath = configDir.appendingPathComponent("Config.xcconfig").path

  try FileManager.default.createDirectory(at: configDir, withIntermediateDirectories: true)
  try configTemplate(values: values).write(
    toFile: configPath,
    atomically: true,
    encoding: .utf8
  )
}

@main
struct BootstrapCommand {
  static func main() {
    runMain {
      let args = normalizeScriptArgs(
        Array(CommandLine.arguments.dropFirst()), scriptName: cli.scriptName)
      cli.preflight(args)
      try parseArguments(args)

      let repoRoot = gitRoot() ?? FileManager.default.currentDirectoryPath
      let completionsPath = URL(fileURLWithPath: repoRoot)
        .appendingPathComponent("scripts")
        .appendingPathComponent("completions.zsh")
        .path

      let zshrcPath = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".zshrc")
        .path

      print("Setting up Saga development environment...")

      let brewPath = try runCommand("which", ["brew"], allowFailure: true, emitOutput: false)
      if brewPath.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
        throw ScriptError("Homebrew is required. Install from https://brew.sh/ and re-run.")
      }

      let repoRootURL = URL(fileURLWithPath: repoRoot)
      print("Installing dependencies from Brewfile...")
      _ = try runCommand(
        "brew",
        ["bundle"],
        cwd: repoRootURL,
        emitOutput: true
      )

      if !isOnePasswordAuthenticated(account: ConfigDefaults.opAccount) {
        print("Authenticating with 1Password...")
        do {
          try signInToOnePassword(account: ConfigDefaults.opAccount)
        } catch {
          throw ScriptError(
            "1Password sign-in failed. Run: op signin --account \(ConfigDefaults.opAccount)"
          )
        }
      }

      let configValues = try resolveConfigValues()
      try writeConfigFile(repoRoot: repoRoot, values: configValues)
      print("Wrote Saga/Config/Config.xcconfig from 1Password")

      // Check if completions are already configured
      let zshrcExists = FileManager.default.fileExists(atPath: zshrcPath)
      var zshrcContent = ""
      if zshrcExists {
        zshrcContent = try String(contentsOfFile: zshrcPath, encoding: .utf8)
      }

      if zshrcContent.contains(completionsPath) {
        print("Completions already configured in \(zshrcPath)")
      } else {
        // Append completions source line
        let sourceLine = "\n# Saga repo script completions\nsource \"\(completionsPath)\"\n"
        let newContent = zshrcContent + sourceLine
        try newContent.write(toFile: zshrcPath, atomically: true, encoding: .utf8)
        print("Added completions to \(zshrcPath)")
      }

      print("")
      print("Done! Restart your shell or run: source ~/.zshrc")
      print("")
      print("Tab completion examples:")
      print("  run <TAB>          - list scripts")
      print("  run format --<TAB> - list script options")
    }
  }
}
