import Foundation

// MARK: - App config file

/// The Contentful credentials that `Config.xcconfig` feeds into the app's Info.plist.
public struct AppConfigValues {
  public let spaceID: String
  public let accessToken: String

  public init(spaceID: String, accessToken: String) {
    self.spaceID = spaceID
    self.accessToken = accessToken
  }
}

public enum AppConfig {
  /// Env var names shared by `run bootstrap`, `run config`, and the 1Password vault items.
  public static let spaceIDKey = "CONTENTFUL_SPACE_ID"
  public static let accessTokenKey = "CONTENTFUL_ACCESS_TOKEN"

  /// Stand-in values for build-only environments (CI) that never talk to Contentful.
  /// Real credentials are only needed to *run* the app, not to compile it.
  public static let placeholderValues = AppConfigValues(
    spaceID: "placeholder",
    accessToken: "placeholder"
  )

  /// Path Xcode resolves `baseConfigurationReferenceRelativePath` to.
  ///
  /// The reference is anchored to the `Saga` synchronized root group, so it lands inside the
  /// app source directory (`Saga/Saga/Config`), not next to the `.xcodeproj` (`Saga/Config`).
  public static func path(repoRoot: String) -> URL {
    URL(fileURLWithPath: repoRoot)
      .appendingPathComponent("Saga")
      .appendingPathComponent("Saga")
      .appendingPathComponent("Config")
      .appendingPathComponent("Config.xcconfig")
  }

  public static func exists(repoRoot: String) -> Bool {
    FileManager.default.fileExists(atPath: path(repoRoot: repoRoot).path)
  }

  /// Reads credentials from the environment, or nil when either is unset or blank.
  public static func valuesFromEnvironment() -> AppConfigValues? {
    guard let spaceID = environmentValue(spaceIDKey),
      let accessToken = environmentValue(accessTokenKey)
    else {
      return nil
    }
    return AppConfigValues(spaceID: spaceID, accessToken: accessToken)
  }

  /// Writes `Config.xcconfig`, creating the directory if needed. Overwrites any existing file.
  @discardableResult
  public static func write(repoRoot: String, values: AppConfigValues) throws -> URL {
    let destination = path(repoRoot: repoRoot)
    try FileManager.default.createDirectory(
      at: destination.deletingLastPathComponent(),
      withIntermediateDirectories: true
    )
    try template(values: values).write(to: destination, atomically: true, encoding: .utf8)
    return destination
  }

  /// A repo-root-relative path, for log output that stays readable.
  public static func displayPath(repoRoot: String) -> String {
    let full = path(repoRoot: repoRoot).path
    let prefix = repoRoot.hasSuffix("/") ? repoRoot : repoRoot + "/"
    return full.hasPrefix(prefix) ? String(full.dropFirst(prefix.count)) : full
  }

  private static func environmentValue(_ key: String) -> String? {
    guard let raw = ProcessInfo.processInfo.environment[key] else { return nil }
    let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
    return trimmed.isEmpty ? nil : trimmed
  }

  private static func template(values: AppConfigValues) -> String {
    """
    //
    //  Config.xcconfig
    //  Saga
    //
    //  Generated by `run bootstrap` / `run config`. Not checked in.
    //

    // Configuration settings file format documentation can be found at:
    // https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project

    \(spaceIDKey) = \(values.spaceID)
    \(accessTokenKey) = \(values.accessToken)
    """
  }
}
